language: rust
rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true
#cache: cargo # This seems to break skeptic for some reason
script:
  - cargo build --verbose --all --features ci
  - cargo test --verbose --all --features ci
